/-
Generated by origin.py from RepresentationTheory/Coinduced.lean
Genuine declarations: 15 of 25 total
Dissolved: 0
Infrastructure skipped: 10
-/
import Origin.Core

/-! # RepresentationTheory on Option α -/

universe u
variable {α : Type u}

def coindV : Submodule k (H → A) where
  carrier := {f : H → A | ∀ (g : G) (h : H), f (φ g * h) = σ g (f h) }
  add_mem' _ _ _ _ := by simp_all
  zero_mem' := by simp
  smul_mem' _ _ _ := by simp_all

def coind : Representation k H (coindV φ ρ) where
  toFun h := (LinearMap.funLeft _ _ (· * h)).restrict fun x hx g h₁ => by
    simpa [mul_assoc] using hx g (h₁ * h)
  map_one' := by ext; simp
  map_mul' _ _ := by ext; simp [mul_assoc]

def coindMap (f : σ.IntertwiningMap ρ) : (coind φ σ).IntertwiningMap (coind φ ρ) where
  __ : _ →ₗ[k] _ := (f.toLinearMap.compLeft H).restrict fun x h ↦ by
    simp only [mem_coindV, LinearMap.compLeft_apply, Function.comp_apply,
      IntertwiningMap.toLinearMap_apply] at h ⊢
    intro g h0
    simpa [h] using LinearMap.ext_iff.1 (f.2 g) (x h0)
  isIntertwining' h := by ext; simp

noncomputable abbrev coind : Rep k H := Rep.of (Representation.coind φ A.ρ)

noncomputable abbrev coindMap {A B : Rep k G} (f : A ⟶ B) : coind φ A ⟶ coind φ B :=
  ofHom <| Representation.coindMap φ f.hom

noncomputable def coindFunctor : Rep.{t} k G ⥤ Rep k H where
  obj A := coind φ A
  map f := coindMap φ f

noncomputable abbrev coind' : Rep k H := Rep.of (Representation.coind' φ A)

lemma coind'_ext {f g : coind' φ A} (hfg : ∀ h, f.hom.toLinearMap (.single h 1) =
    g.hom.toLinearMap (.single h 1)) : f = g :=
  Rep.hom_ext <| by ext1; dsimp; ext h; simpa using hfg h

noncomputable def coindMap' {A B : Rep k G} (f : A ⟶ B) : coind' φ A ⟶ coind' φ B := Rep.ofHom
  { __ := Linear.rightComp k _ f
    isIntertwining' h := by ext; simp }

noncomputable def coindFunctor' : Rep k G ⥤ Rep k H where
  obj A := coind' φ A
  map f := coindMap' φ f

noncomputable def coindVEquiv :
    A.ρ.coindV φ ≃ₗ[k] (res φ (leftRegular k H) ⟶ A) where
  toFun f := Rep.ofHom ⟨linearCombination _ f.1, fun g ↦ by dsimp; ext; simp [f.2 g]⟩
  map_add' _ _ := coind'_ext φ <| by simp [Rep.add_hom]
  map_smul' _ _ := coind'_ext φ <| by simp [smul_hom]
  invFun f := ⟨fun h ↦ f.hom.toLinearMap (.single h 1), fun g h ↦ by
    simp only [res_obj_V, res_obj_ρ, Representation.IntertwiningMap.toLinearMap_apply]
    have := by simpa using (hom_comm_apply f g (.single h 1)).symm
    rw [← this]⟩
  left_inv x := by simp
  right_inv x := coind'_ext φ fun _ => by simp

noncomputable def coindIso : coind φ A ≅ coind' φ A :=
  Rep.mkIso <| .mk (coindVEquiv φ A) fun h => by ext; simp [homEquiv]

noncomputable def coindFunctorIso : coindFunctor k φ ≅ coindFunctor' k φ :=
  NatIso.ofComponents (coindIso φ) fun _ => by
    ext
    exact coind'_ext _ fun _ ↦ by simp [coindIso, coindMap']

def resCoindToHom (B : Rep k H) (A : Rep k G) (f : res φ B ⟶ A) : B ⟶ (coind φ A) :=
  Rep.ofHom ⟨(LinearMap.pi fun h => f.hom.toLinearMap ∘ₗ
    Rep.ρ B h).codRestrict _ fun _ _ _ => by simpa using hom_comm_apply f _ _, fun g ↦ by
    dsimp; ext; simp⟩

noncomputable abbrev resCoindAdjunction : resFunctor.{max w t} φ ⊣ coindFunctor k φ :=
  Adjunction.mkOfHomEquiv {
    homEquiv X Y := (resCoindHomEquiv φ X Y).toEquiv
    homEquiv_naturality_left_symm := by intros; rfl
    homEquiv_naturality_right := by intros; ext; rfl }

