/-
Generated by origin.py from CategoryTheory/Limits/Shapes/Pullback/ChosenPullback.lean
Genuine declarations: 27 of 36 total
Dissolved: 0
Infrastructure skipped: 9
-/
import Origin.Core

/-! # CategoryTheory.Limits.Shapes.Pullback on Option α -/

universe u
variable {α : Type u}

structure ChosenPullback {X₁ X₂ S : C} (f₁ : X₁ ⟶ S) (f₂ : X₂ ⟶ S) where
  /-- the pullback -/
  pullback : C
  /-- the first projection -/
  p₁ : pullback ⟶ X₁
  /-- the second projection -/
  p₂ : pullback ⟶ X₂
  condition : p₁ ≫ f₁ = p₂ ≫ f₂
  /-- `pullback` is a pullback of `f₁` and `f₂` -/
  isLimit : IsLimit (PullbackCone.mk _ _ condition)
  /-- the projection `pullback ⟶ S` -/
  p : pullback ⟶ S := p₁ ≫ f₁
  hp₁ : p₁ ≫ f₁ = p := by cat_disch

lemma hp₂ : h.p₂ ≫ f₂ = h.p := by rw [← h.condition, hp₁]

structure LiftStruct {Y : C} (g₁ : Y ⟶ X₁) (g₂ : Y ⟶ X₂) (b : Y ⟶ S) where
  /-- a lifting to the pullback -/
  f : Y ⟶ h.pullback
  f_p₁ : f ≫ h.p₁ = g₁ := by cat_disch
  f_p₂ : f ≫ h.p₂ = g₂ := by cat_disch
  f_p : f ≫ h.p = b := by cat_disch

lemma w (l : h.LiftStruct g₁ g₂ b) : g₁ ≫ f₁ = g₂ ≫ f₂ := by
  simp only [← l.f_p₁, ← l.f_p₂, Category.assoc, h.condition]

abbrev Diagonal := h.LiftStruct (𝟙 X) (𝟙 X) f

structure ChosenPullback₃ where
  /-- A chosen pullback of `h₁₂.pullback` and `h₂₃.pullback` over `X₂`. -/
  chosenPullback : ChosenPullback h₁₂.p₂ h₂₃.p₁
  /-- The projection from the wide pullback of `(f₁, f₂, f₃)` to `S`. -/
  p : chosenPullback.pullback ⟶ S := chosenPullback.p₁ ≫ h₁₂.p
  /-- The projection from the wide pullback of `(f₁, f₂, f₃)` to `X₁`. -/
  p₁ : chosenPullback.pullback ⟶ X₁ := chosenPullback.p₁ ≫ h₁₂.p₁
  /-- The projection from the wide pullback of `(f₁, f₂, f₃)` to `X₃`. -/
  p₃ : chosenPullback.pullback ⟶ X₃ := chosenPullback.p₂ ≫ h₂₃.p₂
  /-- A morphism from the wide pullback `(f₁, f₂, f₃)` to the pullback of `f₁` and `f₃`
  that is compatible with projections. -/
  l : h₁₃.LiftStruct p₁ p₃ p
  hp₁ : chosenPullback.p₁ ≫ h₁₂.p₁ = p₁ := by cat_disch
  hp₃ : chosenPullback.p₂ ≫ h₂₃.p₂ = p₃ := by cat_disch

abbrev pullback := h.chosenPullback.pullback

def p₁₃ : h.pullback ⟶ h₁₃.pullback := h.l.f

def p₁₂ : h.pullback ⟶ h₁₂.pullback := h.chosenPullback.p₁

def p₂₃ : h.pullback ⟶ h₂₃.pullback := h.chosenPullback.p₂

def p₂ : h.pullback ⟶ X₂ := h.chosenPullback.p

lemma p₁₂_p₁ : h.p₁₂ ≫ h₁₂.p₁ = h.p₁ := by simp [p₁₂, hp₁]

lemma p₁₂_p₂ : h.p₁₂ ≫ h₁₂.p₂ = h.p₂ := by simp [p₁₂, p₂]

lemma p₂₃_p₂ : h.p₂₃ ≫ h₂₃.p₁ = h.p₂ := by simp [p₂₃, p₂]

lemma p₂₃_p₃ : h.p₂₃ ≫ h₂₃.p₂ = h.p₃ := by simp [p₂₃, hp₃]

lemma p₁₃_p₁ : h.p₁₃ ≫ h₁₃.p₁ = h.p₁ := by simp [p₁₃]

lemma p₁₃_p₃ : h.p₁₃ ≫ h₁₃.p₂ = h.p₃ := by simp [p₁₃]

lemma w₁ : h.p₁ ≫ f₁ = h.p := by
  simpa only [← hp₁, Category.assoc, h₁₃.hp₁, h.l.f_p] using h.l.f_p₁.symm =≫ f₁

lemma w₃ : h.p₃ ≫ f₃ = h.p := by
  simpa only [← hp₃, Category.assoc, h₁₃.hp₂, h.l.f_p] using h.l.f_p₂.symm =≫ f₃

lemma w₂ : h.p₂ ≫ f₂ = h.p := by
  rw [← p₂₃_p₂_assoc, h₂₃.condition, ← w₃, p₂₃_p₃_assoc]

lemma p₁₂_p : h.p₁₂ ≫ h₁₂.p = h.p := by
  rw [← h₁₂.hp₂, p₁₂_p₂_assoc, w₂]

lemma p₂₃_p : h.p₂₃ ≫ h₂₃.p = h.p := by
  rw [← h₂₃.hp₂, p₂₃_p₃_assoc, w₃]

lemma p₁₃_p : h.p₁₃ ≫ h₁₃.p = h.p := by
  rw [← h₁₃.hp₁, p₁₃_p₁_assoc, w₁]

lemma p₁₂_eq_lift : h.p₁₂ = h₁₂.isPullback.lift h.p₁ h.p₂ (by simp) := by
  cat_disch

lemma p₂₃_eq_lift : h.p₂₃ = h₂₃.isPullback.lift h.p₂ h.p₃ (by simp) := by
  cat_disch

lemma p₁₃_eq_lift : h.p₁₃ = h₁₃.isPullback.lift h.p₁ h.p₃ (by simp) := by
  cat_disch

lemma hom_ext {Y : C} {φ φ' : Y ⟶ h.pullback}
    (h₁ : φ ≫ h.p₁ = φ' ≫ h.p₁) (h₂ : φ ≫ h.p₂ = φ' ≫ h.p₂)
    (h₃ : φ ≫ h.p₃ = φ' ≫ h.p₃) : φ = φ' := by
  apply h.isPullback₂.hom_ext <;> cat_disch

