/-
Generated by origin.py from FieldTheory/Finite/Valuation.lean
Genuine declarations: 1 of 3 total
Dissolved: 1
Infrastructure skipped: 1
-/
import Origin.Core

/-! # FieldTheory.Finite on Option α -/

universe u
variable {α : Type u}

lemma valuation_algebraMap_le_one (v : Valuation A Γ) (a : Fq) :
    v (algebraMap Fq A a) ≤ 1 := by by_cases a = 0 <;> grind [zero_le']

