/-
Generated by origin.py from Data/Array/Defs.lean
Genuine declarations: 2 of 2 total
Dissolved: 0
Infrastructure skipped: 0
-/
import Origin.Core

/-! # Data.Array on Option α -/

universe u
variable {α : Type u}

def cyclicPermute! [Inhabited α] : Array α → List Nat → Array α
  | a, [] => a
  | a, i :: is => cyclicPermuteAux a is a[i]! i

def permute! [Inhabited α] (a : Array α) (ls : List (List Nat)) : Array α :=

