/-
Generated by origin.py from Probability/Kernel/Invariance.lean
Genuine declarations: 4 of 5 total
Dissolved: 0
Infrastructure skipped: 1
-/
import Origin.Core

/-! # Probability.Kernel on Option α -/

universe u
variable {α : Type u}

def Invariant (κ : Kernel α α) (μ : Measure α) : Prop :=
  μ.bind κ = μ

theorem Invariant.def (hκ : Invariant κ μ) : μ.bind κ = μ :=
  hκ

theorem Invariant.comp (hκ : Invariant κ μ) (hη : Invariant η μ) :
    Invariant (κ ∘ₖ η) μ := by
  rcases isEmpty_or_nonempty α with _ | hα
  · exact Subsingleton.elim _ _
  · rw [Invariant, ← Measure.comp_assoc, hη, hκ]

def IsReversible (κ : Kernel α α) (π : Measure α) : Prop :=
  ∀ ⦃A B⦄, MeasurableSet A → MeasurableSet B →
    ∫⁻ x in A, κ x B ∂π = ∫⁻ x in B, κ x A ∂π

