/-
Extracted from ModelTheory/Topology/Types.lean
Genuine: 3 of 6 | Dissolved: 0 | Infrastructure: 3
-/
import Origin.Core

/-!
# Topology on the space of complete types

This file defines a topological structure on the type `CompleteType T α` (note that
these are types from model theory and not types from type theory). The topology
is generated by sets of the form `{p : CompleteType T α | ∃ φ, φ ∈ p}`.

Note that the contents of this file are separate from `Mathlib/ModelTheory/Types.lean`
to avoid importing files from the Topology folder there.
-/

open Set FirstOrder Language Theory CompleteType TopologicalSpace

namespace CompleteType

universe u

variable {L : Language} {T : L.Theory} {α : Type*}

-- INSTANCE (free from Core): :

public lemma isOpen_typesWith (φ : L[[α]].Sentence) : IsOpen (T.typesWith φ) :=
  isOpen_generateFrom_of_mem ⟨φ, rfl⟩

public lemma isClosed_typesWith (φ : L[[α]].Sentence) : IsClosed (T.typesWith φ) where
  isOpen_compl := by rw [← typesWith_not]; exact isOpen_typesWith _

public lemma isClopen_typesWith (φ : L[[α]].Sentence) : IsClopen (T.typesWith φ) where
  left := isClosed_typesWith _
  right := isOpen_typesWith _

-- INSTANCE (free from Core): :

end CompleteType
