/-
Generated by origin.py from RingTheory/Ideal/BigOperators.lean
Genuine declarations: 1 of 1 total
Dissolved: 0
Infrastructure skipped: 0
-/
import Origin.Core

/-! # RingTheory.Ideal on Option α -/

universe u
variable {α : Type u}

theorem sum_mem (I : Ideal α) {ι : Type*} {t : Finset ι} {f : ι → α} :
    (∀ c ∈ t, f c ∈ I) → (∑ i ∈ t, f i) ∈ I :=
  Submodule.sum_mem I

