/-
Generated by origin.py from Algebra/Category/ModuleCat/Sheaf/Localization.lean
Genuine declarations: 1 of 2 total
Dissolved: 0
Infrastructure skipped: 1
-/
import Origin.Core

/-! # Algebra.Category.ModuleCat.Sheaf on Option α -/

universe u
variable {α : Type u}

lemma inverseImage_W_toPresheaf_eq_inverseImage_isomorphisms :
    J.W.inverseImage (toPresheaf R₀) = (isomorphisms _).inverseImage (sheafification α) := by
  rw [J.W_eq_inverseImage_isomorphisms]
  ext P Q f
  simp only [inverseImage_iff, isomorphisms.iff,
    ← isIso_iff_of_reflects_iso _ (SheafOfModules.toSheaf.{v} R)]
  exact (isomorphisms _).arrow_mk_iso_iff
    (((Functor.mapArrowFunctor _ _).mapIso (sheafificationCompToSheaf.{v} α)).app (Arrow.mk f))

