/-
Generated by origin.py from Algebra/Order/GroupWithZero/Lex.lean
Genuine declarations: 1 of 10 total
Dissolved: 9
Infrastructure skipped: 0
-/
import Origin.Core

/-! # Algebra.Order.GroupWithZero on Option α -/

universe u
variable {α : Type u}

theorem fst_comp_inl : (fst _ _).comp (inl α β) = .id α := by
  ext x
  obtain rfl | ⟨_, rfl⟩ := GroupWithZero.eq_zero_or_unit x <;>
  simp

