/-
Released under MIT license.
-/
import Origin.Core

/-!
# Ring Theory on Option α (Core-based)

**Category 2** — pure math, no zero-management infrastructure.

Mathlib RingTheory: 211 files, 99,382 lines, 7,963 genuine declarations.
Origin restates every concept once, in minimum form.

Ideals, localization, Noetherian/Artinian, Dedekind domains, PID,
polynomial rings, graded rings, tensor products, flat modules,
Chinese remainder, valuations, integral closure, Jacobson radical,
Krull dimension, completion, power series.
-/

universe u
variable {α β : Type u}

-- ============================================================================
-- 1. IDEALS
-- ============================================================================

/-- An ideal of a ring: closed under addition and absorption. -/
structure RingIdeal (α : Type u) [Mul α] [Add α] where
  mem : α → Prop
  add_closed : ∀ a b, mem a → mem b → mem (a + b)
  mul_absorb : ∀ r a, mem a → mem (r * a)

/-- Ideal membership on Option: none is not in any ideal. -/
def idealMem [Mul α] [Add α] (I : RingIdeal α) : Option α → Prop :=
  liftPred I.mem

@[simp] theorem idealMem_none [Mul α] [Add α] (I : RingIdeal α) :
    idealMem I none = False := rfl

@[simp] theorem idealMem_some [Mul α] [Add α] (I : RingIdeal α) (a : α) :
    idealMem I (some a) = I.mem a := rfl

/-- A prime ideal: ab ∈ I implies a ∈ I or b ∈ I. -/
def isPrimeIdeal' [Mul α] [Add α] (I : RingIdeal α) : Prop :=
  ∀ a b, I.mem (a * b) → I.mem a ∨ I.mem b

/-- A maximal ideal: not contained in any proper larger ideal. -/
def isMaximal' [Mul α] [Add α] (I : RingIdeal α) : Prop :=
  ∀ J : RingIdeal α, (∀ a, I.mem a → J.mem a) → (∃ a, J.mem a ∧ ¬I.mem a) →
    ∀ b, J.mem b

/-- The radical of an ideal: √I = {a | aⁿ ∈ I for some n}. -/
def radicalIdeal [Mul α] [Add α] (I : RingIdeal α)
    (powF : α → Nat → α) : α → Prop :=
  fun a => ∃ n, I.mem (powF a n)

/-- The Jacobson radical: intersection of all maximal ideals. -/
def jacobsonRadical [Mul α] [Add α] (isMax : RingIdeal α → Prop)
    (allIdeals : RingIdeal α → Prop) : α → Prop :=
  fun a => ∀ I, allIdeals I → isMax I → I.mem a

/-- Nakayama's lemma (abstract): M = IM implies M = 0 for f.g. modules. -/
def nakayama (isFinGen : Prop) (mEqualsIM : Prop) (mIsZero : Prop) : Prop :=
  isFinGen → mEqualsIM → mIsZero

-- ============================================================================
-- 2. LOCALIZATION
-- ============================================================================

/-- A multiplicative subset. -/
structure MulSubset (α : Type u) [Mul α] where
  mem : α → Prop
  mul_closed : ∀ a b, mem a → mem b → mem (a * b)

/-- Localization universal property: lifts through Option.map. -/
theorem localize_universal (loc f g : α → α) (v : Option α)
    (h : ∀ a, f a = g (loc a)) :
    Option.map f v = Option.map g (Option.map loc v) := by
  cases v <;> simp [h]

-- ============================================================================
-- 3. NOETHERIAN AND ARTINIAN
-- ============================================================================

/-- Noetherian: ascending chain condition on ideals. -/
def isNoetherian' [Mul α] [Add α] : Prop :=
  ∀ chain : Nat → RingIdeal α,
    (∀ n, ∀ a, (chain n).mem a → (chain (n + 1)).mem a) →
    ∃ N, ∀ n, N ≤ n → ∀ a, (chain n).mem a ↔ (chain N).mem a

/-- Artinian: descending chain condition on ideals. -/
def isArtinian' [Mul α] [Add α] : Prop :=
  ∀ chain : Nat → RingIdeal α,
    (∀ n, ∀ a, (chain (n + 1)).mem a → (chain n).mem a) →
    ∃ N, ∀ n, N ≤ n → ∀ a, (chain n).mem a ↔ (chain N).mem a

/-- Hilbert basis theorem (abstract): R Noetherian ⟹ R[x] Noetherian. -/
def hilbertBasis (rNoeth polyNoeth : Prop) : Prop :=
  rNoeth → polyNoeth

-- ============================================================================
-- 4. DEDEKIND DOMAINS AND PID
-- ============================================================================

/-- Dedekind domain: Noetherian + every nonzero prime is maximal. -/
def isDedekind' [Mul α] [Add α] : Prop :=
  isNoetherian' (α := α) ∧ ∀ I : RingIdeal α, isPrimeIdeal' I → isMaximal' I

/-- Principal ideal domain: every ideal is generated by one element. -/
def isPID' [Mul α] [Add α] : Prop :=
  ∀ I : RingIdeal α, ∃ g, ∀ a, I.mem a → ∃ r, r * g = a

/-- UFD: unique factorization into irreducibles. -/
def isUFD (factorF : α → List α) (isIrred : α → Prop)
    (_assocF : α → α → Prop) : Prop :=
  (∀ a, ∀ p ∈ factorF a, isIrred p) ∧
  (∀ a f₁ f₂, factorF a = f₁ → factorF a = f₂ → f₁.length = f₂.length)

-- ============================================================================
-- 5. POLYNOMIALS
-- ============================================================================

/-- Polynomial evaluation is a ring homomorphism. -/
def polyEval [Mul α] [Add α] (evalF : (Nat → α) → α → α) (coeffs : Nat → α)
    (x : α) : Option α :=
  some (evalF coeffs x)

/-- Irreducible polynomial: cannot be factored nontrivially. -/
def isIrredPoly (isUnit : α → Prop) (factorF : α → α × α) : α → Prop :=
  fun p => ∀ a b, factorF p = (a, b) → isUnit a ∨ isUnit b

-- ============================================================================
-- 6. GRADED RINGS
-- ============================================================================

/-- Grade of an element lifts to Option. -/
def gradeOf (gradeF : α → Nat) : Option α → Option Nat :=
  Option.map gradeF

@[simp] theorem gradeOf_none (gradeF : α → Nat) :
    gradeOf gradeF (none : Option α) = none := rfl

@[simp] theorem gradeOf_some (gradeF : α → Nat) (a : α) :
    gradeOf gradeF (some a) = some (gradeF a) := rfl

/-- Grades add under multiplication: grade(a·b) = grade(a) + grade(b). -/
theorem graded_mul [Mul α] (gradeF : α → Nat)
    (h : ∀ a b, gradeF (a * b) = gradeF a + gradeF b) (a b : α) :
    gradeOf gradeF (some a * some b) = some (gradeF a + gradeF b) := by
  simp [gradeOf, h]

-- ============================================================================
-- 7. TENSOR PRODUCT AND BASE CHANGE
-- ============================================================================

/-- Base change: apply a ring map to the first component. -/
def baseChange (f : α → α) : Option (α × β) → Option (α × β) :=
  Option.map (fun p => (f p.1, p.2))

theorem baseChange_none (f : α → α) :
    baseChange f (none : Option (α × β)) = none := rfl

theorem baseChange_some (f : α → α) (a : α) (b : β) :
    baseChange f (some (a, b)) = some (f a, b) := rfl

/-- Base change roundtrip: extend then restrict recovers the original. -/
theorem restrict_extend (f g : α → α) (v : Option (α × β))
    (h : ∀ a, g (f a) = a) : baseChange g (baseChange f v) = v := by
  cases v with
  | none => rfl
  | some p => simp [baseChange, h]

-- ============================================================================
-- 8. FLAT MODULES
-- ============================================================================

/-- A module is flat: tensoring preserves injectivity. -/
def isFlat' (tensorF : α → α → α) : Prop :=
  ∀ f : α → α, (∀ a b, f a = f b → a = b) →
    ∀ a b, tensorF (f a) b = tensorF (f b) b → f a = f b

-- ============================================================================
-- 9. INTEGRAL CLOSURE AND KRULL DIMENSION
-- ============================================================================

/-- An element is integral over a subring: root of a monic polynomial. -/
def isIntegralOver (monicRootF : α → Prop) : α → Prop := monicRootF

/-- The integral closure: all elements integral over R. -/
def integralClosure (isIntegral : α → Prop) : α → Prop := isIntegral

/-- Krull dimension: supremum of lengths of chains of prime ideals. -/
def krullDimension (maxChainLength : Nat) : Nat := maxChainLength

-- ============================================================================
-- 10. COMPLETION AND POWER SERIES
-- ============================================================================

/-- Completion of a ring at an ideal (abstract). -/
def completion (completeF : α → α) : α → α := completeF

/-- Formal power series: functions Nat → R. -/
def PowerSeries := Nat → α

-- ============================================================================
-- 11. CHINESE REMAINDER THEOREM
-- ============================================================================

/-- CRT: simultaneous quotient maps lift through Option. -/
theorem chinese_remainder (q₁ q₂ : α → α) (v : Option α) :
    Option.map (fun a => (q₁ a, q₂ a)) v =
    liftBin₂ Prod.mk (Option.map q₁ v) (Option.map q₂ v) := by
  cases v <;> simp

-- ============================================================================
-- 12. VALUATIONS
-- ============================================================================

/-- A valuation: multiplicative function to an ordered group. -/
def IsValuation [Mul α] [Add α] (v : α → β) (mulB : β → β → β)
    (leB : β → β → Prop) (maxB : β → β → β) : Prop :=
  (∀ a b, v (a * b) = mulB (v a) (v b)) ∧
  (∀ a b, leB (v (a + b)) (maxB (v a) (v b)))

-- ============================================================================
-- STUBS — auto-generated by: python3 scripts/origin.py stub RingTheory
-- Upgrade key declarations from stubs to real structures/theorems.
-- ============================================================================

-- AdicCompletion/Algebra.lean

-- AdicCompletion/AsTensorProduct.lean

-- AdicCompletion/Basic.lean

-- AdicCompletion/Exactness.lean

-- AdicCompletion/Functoriality.lean

-- Adjoin/Basic.lean

-- Adjoin/Dimension.lean

-- Adjoin/FG.lean

-- Adjoin/Field.lean

-- Adjoin/PowerBasis.lean

-- Adjoin/Tower.lean

-- AdjoinRoot.lean

-- AlgebraTower.lean

-- Algebraic/Basic.lean

-- Algebraic/Cardinality.lean

-- Algebraic/Defs.lean

-- Algebraic/Integral.lean

-- Algebraic/LinearIndependent.lean

-- Algebraic/MvPolynomial.lean

-- Algebraic/Pi.lean

-- AlgebraicIndependent.lean

-- Artinian.lean

-- Bezout.lean

-- Bialgebra/Basic.lean

-- Bialgebra/Equiv.lean
-- COLLISION: apply' already in Order.lean — rename needed
-- COLLISION: refl' already in SetTheory.lean — rename needed
-- COLLISION: symm' already in SetTheory.lean — rename needed
-- COLLISION: symm_apply' already in Order.lean — rename needed

-- Bialgebra/Hom.lean
-- COLLISION: congr_fun' already in Order.lean — rename needed
-- COLLISION: copy' already in Order.lean — rename needed
-- COLLISION: id' already in Order.lean — rename needed

-- Bialgebra/TensorProduct.lean

-- Binomial.lean

-- ChainOfDivisors.lean

-- ClassGroup.lean

-- Coalgebra/Basic.lean

-- Coalgebra/Equiv.lean

-- Coalgebra/Hom.lean

-- Coalgebra/TensorProduct.lean

-- Complex.lean

-- Congruence/Basic.lean

-- Congruence/BigOperators.lean

-- Congruence/Defs.lean
-- COLLISION: add' already in Order.lean — rename needed
-- COLLISION: mul' already in Order.lean — rename needed
-- COLLISION: sub' already in SetTheory.lean — rename needed

-- Congruence/Opposite.lean

-- Coprime/Basic.lean

-- Coprime/Ideal.lean

-- Coprime/Lemmas.lean

-- DedekindDomain/AdicValuation.lean

-- DedekindDomain/Basic.lean

-- DedekindDomain/Different.lean

-- DedekindDomain/Dvr.lean

-- DedekindDomain/Factorization.lean

-- DedekindDomain/FiniteAdeleRing.lean

-- DedekindDomain/Ideal.lean

-- DedekindDomain/IntegralClosure.lean
-- COLLISION: isNoetherian' already in RingTheory2.lean — rename needed
-- COLLISION: rank' already in SetTheory.lean — rename needed

-- DedekindDomain/PID.lean

-- DedekindDomain/SInteger.lean

-- DedekindDomain/SelmerGroup.lean

-- Derivation/Basic.lean

-- Derivation/DifferentialRing.lean

-- Derivation/MapCoeffs.lean

-- Derivation/ToSquareZero.lean

-- DiscreteValuationRing/Basic.lean

-- DiscreteValuationRing/TFAE.lean

-- Discriminant.lean

-- DividedPowers/Basic.lean

-- DualNumber.lean

-- EisensteinCriterion.lean

-- EssentialFiniteness.lean

-- Etale/Basic.lean

-- Etale/Field.lean

-- EuclideanDomain.lean

-- Extension.lean

-- Filtration.lean

-- FiniteLength.lean

-- FinitePresentation.lean

-- FiniteStability.lean

-- FiniteType.lean

-- Finiteness/Basic.lean

-- Finiteness/Bilinear.lean
-- COLLISION: map₂' already in SetTheory.lean — rename needed

-- Finiteness/Cardinality.lean

-- Finiteness/Defs.lean

-- Finiteness/Finsupp.lean

-- Finiteness/Ideal.lean

-- Finiteness/Nakayama.lean

-- Finiteness/Nilpotent.lean

-- Finiteness/Prod.lean

-- Finiteness/Projective.lean

-- Finiteness/Subalgebra.lean

-- Finiteness/TensorProduct.lean

-- Fintype.lean

-- Flat/Algebra.lean

-- Flat/Basic.lean

-- Flat/CategoryTheory.lean

-- Flat/Equalizer.lean

-- Flat/EquationalCriterion.lean

-- Flat/FaithfullyFlat.lean

-- Flat/Stability.lean

-- FractionalIdeal/Basic.lean

-- FractionalIdeal/Extended.lean

-- FractionalIdeal/Norm.lean

-- FractionalIdeal/Operations.lean

-- FreeCommRing.lean

-- FreeRing.lean

-- Generators.lean

-- GradedAlgebra/Basic.lean

-- GradedAlgebra/HomogeneousIdeal.lean

-- GradedAlgebra/HomogeneousLocalization.lean

-- GradedAlgebra/Radical.lean
-- COLLISION: radical' already in Order.lean — rename needed

-- HahnSeries/Addition.lean

-- HahnSeries/Basic.lean

-- HahnSeries/Multiplication.lean

-- HahnSeries/PowerSeries.lean

-- HahnSeries/Summable.lean
-- COLLISION: isUnit_iff' already in SetTheory.lean — rename needed

-- HahnSeries/Valuation.lean

-- Henselian.lean

-- HopfAlgebra.lean

-- Ideal/AssociatedPrime.lean

-- Ideal/Basic.lean

-- Ideal/Basis.lean

-- Ideal/BigOperators.lean

-- Ideal/Colon.lean

-- Ideal/Cotangent.lean

-- Ideal/Defs.lean

-- Ideal/IdempotentFG.lean

-- Ideal/IsPrimary.lean

-- Ideal/IsPrincipal.lean

-- Ideal/IsPrincipalPowQuotient.lean

-- Ideal/Lattice.lean
-- COLLISION: mem_iInf' already in Order.lean — rename needed

-- Ideal/Maps.lean

-- Ideal/Maximal.lean

-- Ideal/MinimalPrime.lean

-- Ideal/Nonunits.lean

-- Ideal/Norm/AbsNorm.lean

-- Ideal/Norm/RelNorm.lean

-- Ideal/Operations.lean

-- Ideal/Over.lean

-- Ideal/Pointwise.lean

-- Ideal/Prime.lean

-- Ideal/Prod.lean

-- Ideal/Quotient/Basic.lean

-- Ideal/Quotient/Defs.lean

-- Ideal/Quotient/Nilpotent.lean

-- Ideal/Quotient/Operations.lean

-- Ideal/Span.lean

-- Idempotents.lean

-- Int/Basic.lean

-- IntegralClosure/Algebra/Basic.lean
-- COLLISION: smul' already in Order.lean — rename needed

-- IntegralClosure/Algebra/Defs.lean

-- IntegralClosure/IntegralRestrict.lean

-- IntegralClosure/IntegrallyClosed.lean

-- IntegralClosure/IsIntegral/Basic.lean

-- IntegralClosure/IsIntegral/Defs.lean

-- IntegralClosure/IsIntegralClosure/Basic.lean

-- IntegralClosure/IsIntegralClosure/Defs.lean

-- IntegralDomain.lean

-- IsAdjoinRoot.lean

-- IsPrimary.lean

-- IsTensorProduct.lean

-- Jacobson.lean

-- JacobsonIdeal.lean

-- Kaehler/Basic.lean

-- Kaehler/CotangentComplex.lean

-- Kaehler/Polynomial.lean

-- Kaehler/TensorProduct.lean

-- KrullDimension/Basic.lean

-- KrullDimension/Field.lean

-- Lasker.lean

-- LaurentSeries.lean

-- LinearDisjoint.lean

-- LittleWedderburn.lean

-- LocalProperties/Basic.lean

-- LocalProperties/Exactness.lean

-- LocalProperties/IntegrallyClosed.lean

-- LocalProperties/Projective.lean

-- LocalProperties/Reduced.lean

-- LocalProperties/Submodule.lean

-- LocalRing/Basic.lean

-- LocalRing/MaximalIdeal/Basic.lean

-- LocalRing/MaximalIdeal/Defs.lean

-- LocalRing/Module.lean

-- LocalRing/Quotient.lean

-- LocalRing/ResidueField/Basic.lean

-- LocalRing/ResidueField/Defs.lean

-- LocalRing/RingHom/Basic.lean

-- LocalRing/Subring.lean

-- Localization/Algebra.lean

-- Localization/AsSubring.lean

-- Localization/AtPrime.lean

-- Localization/Away/AdjoinRoot.lean

-- Localization/Away/Basic.lean

-- Localization/Away/Lemmas.lean

-- Localization/BaseChange.lean

-- Localization/Basic.lean

-- Localization/Cardinality.lean

-- Localization/Defs.lean

-- Localization/Finiteness.lean

-- Localization/FractionRing.lean

-- Localization/Free.lean

-- Localization/Ideal.lean

-- Localization/Integer.lean

-- Localization/Integral.lean

-- Localization/InvSubmonoid.lean

-- Localization/LocalizationLocalization.lean

-- Localization/Module.lean

-- Localization/NormTrace.lean

-- Localization/NumDen.lean

-- Localization/Submodule.lean

-- MatrixAlgebra.lean

-- MaximalSpectrum.lean

-- Multiplicity.lean

-- MvPolynomial.lean

-- MvPolynomial/Basic.lean

-- MvPolynomial/FreeCommRing.lean

-- MvPolynomial/Homogeneous.lean

-- MvPolynomial/Ideal.lean

-- MvPolynomial/Localization.lean

-- MvPolynomial/Symmetric/Defs.lean

-- MvPolynomial/Symmetric/FundamentalTheorem.lean

-- MvPolynomial/Symmetric/NewtonIdentities.lean

-- MvPolynomial/Tower.lean

-- MvPolynomial/WeightedHomogeneous.lean

-- MvPowerSeries/Basic.lean

-- MvPowerSeries/Inverse.lean

-- MvPowerSeries/LexOrder.lean

-- MvPowerSeries/Order.lean

-- MvPowerSeries/Trunc.lean

-- Nakayama.lean

-- Nilpotent/Basic.lean

-- Nilpotent/Defs.lean

-- Nilpotent/Lemmas.lean

-- Noetherian/Basic.lean

-- Noetherian/Defs.lean

-- Noetherian/Filter.lean

-- Noetherian/Nilpotent.lean

-- Noetherian/Orzech.lean

-- NonUnitalSubring/Basic.lean

-- NonUnitalSubring/Defs.lean
-- COLLISION: inclusion' already in Order.lean — rename needed

-- NonUnitalSubsemiring/Basic.lean

-- NonUnitalSubsemiring/Defs.lean

-- Norm/Basic.lean

-- Norm/Defs.lean

-- NormTrace.lean

-- Nullstellensatz.lean

-- OreLocalization/Basic.lean

-- OreLocalization/Cardinality.lean

-- OreLocalization/OreSet.lean

-- OreLocalization/Ring.lean

-- OrzechProperty.lean

-- Perfection.lean

-- PiTensorProduct.lean

-- Polynomial/Basic.lean

-- Polynomial/Bernstein.lean

-- Polynomial/Chebyshev.lean

-- Polynomial/Content.lean

-- Polynomial/Cyclotomic/Basic.lean

-- Polynomial/Cyclotomic/Eval.lean

-- Polynomial/Cyclotomic/Expand.lean

-- Polynomial/Cyclotomic/Roots.lean

-- Polynomial/Dickson.lean

-- Polynomial/Eisenstein/Basic.lean

-- Polynomial/Eisenstein/IsIntegral.lean

-- Polynomial/GaussLemma.lean

-- Polynomial/Hermite/Basic.lean

-- Polynomial/Hermite/Gaussian.lean

-- Polynomial/IntegralNormalization.lean

-- Polynomial/IrreducibleRing.lean

-- Polynomial/Nilpotent.lean

-- Polynomial/Opposites.lean

-- Polynomial/Pochhammer.lean

-- Polynomial/Quotient.lean

-- Polynomial/Radical.lean

-- Polynomial/RationalRoot.lean

-- Polynomial/ScaleRoots.lean

-- Polynomial/Selmer.lean

-- Polynomial/SeparableDegree.lean

-- Polynomial/Tower.lean

-- Polynomial/UniqueFactorization.lean

-- Polynomial/Vieta.lean

-- Polynomial/Wronskian.lean

-- PolynomialAlgebra.lean

-- PowerBasis.lean

-- PowerSeries/Basic.lean

-- PowerSeries/Derivative.lean

-- PowerSeries/Inverse.lean

-- PowerSeries/Order.lean

-- PowerSeries/Trunc.lean

-- PowerSeries/WellKnown.lean

-- Presentation.lean

-- Prime.lean

-- PrimeSpectrum.lean

-- PrincipalIdealDomain.lean

-- PrincipalIdealDomainOfPrime.lean

-- QuotSMulTop.lean

-- Radical.lean

-- ReesAlgebra.lean

-- Regular/IsSMulRegular.lean

-- Regular/RegularSequence.lean

-- RingHom/Finite.lean

-- RingHom/FinitePresentation.lean

-- RingHom/FiniteType.lean

-- RingHom/Injective.lean

-- RingHom/Integral.lean

-- RingHom/Locally.lean

-- RingHom/StandardSmooth.lean

-- RingHom/Surjective.lean

-- RingHomProperties.lean

-- RingInvo.lean

-- RootsOfUnity/Basic.lean

-- RootsOfUnity/Complex.lean

-- RootsOfUnity/EnoughRootsOfUnity.lean

-- RootsOfUnity/Lemmas.lean

-- RootsOfUnity/Minpoly.lean

-- RootsOfUnity/PrimitiveRoots.lean

-- SimpleModule.lean

-- SimpleRing/Basic.lean

-- SimpleRing/Defs.lean

-- SimpleRing/Field.lean

-- Smooth/Basic.lean
-- COLLISION: Smooth' already in Geometry2.lean — rename needed

-- Smooth/Kaehler.lean

-- Smooth/Pi.lean

-- Smooth/StandardSmooth.lean

-- Support.lean

-- SurjectiveOnStalks.lean

-- TensorProduct/Basic.lean

-- TensorProduct/Finite.lean

-- TensorProduct/Free.lean

-- TensorProduct/MvPolynomial.lean

-- TensorProduct/Pi.lean

-- Trace/Basic.lean

-- Trace/Defs.lean

-- Trace/Quotient.lean

-- TwoSidedIdeal/Basic.lean

-- TwoSidedIdeal/BigOperators.lean

-- TwoSidedIdeal/Kernel.lean

-- TwoSidedIdeal/Lattice.lean

-- TwoSidedIdeal/Operations.lean

-- UniqueFactorizationDomain/Basic.lean

-- UniqueFactorizationDomain/Defs.lean

-- UniqueFactorizationDomain/FactorSet.lean

-- UniqueFactorizationDomain/Finite.lean

-- UniqueFactorizationDomain/Finsupp.lean

-- UniqueFactorizationDomain/GCDMonoid.lean

-- UniqueFactorizationDomain/Ideal.lean

-- UniqueFactorizationDomain/Multiplicative.lean

-- UniqueFactorizationDomain/Multiplicity.lean

-- UniqueFactorizationDomain/Nat.lean

-- UniqueFactorizationDomain/NormalizedFactors.lean

-- Unramified/Basic.lean

-- Unramified/Field.lean

-- Unramified/Finite.lean

-- Unramified/Pi.lean

-- Valuation/AlgebraInstances.lean

-- Valuation/Basic.lean

-- Valuation/ExtendToLocalization.lean

-- Valuation/Integers.lean

-- Valuation/Integral.lean

-- Valuation/LocalSubring.lean

-- Valuation/Minpoly.lean

-- Valuation/PrimeMultiplicity.lean

-- Valuation/Quotient.lean

-- Valuation/RamificationGroup.lean

-- Valuation/RankOne.lean

-- Valuation/ValExtension.lean

-- Valuation/ValuationRing.lean

-- Valuation/ValuationSubring.lean

-- WittVector/Basic.lean

-- WittVector/Compare.lean

-- WittVector/Defs.lean

-- WittVector/DiscreteValuationRing.lean

-- WittVector/Domain.lean

-- WittVector/Frobenius.lean

-- WittVector/FrobeniusFractionField.lean

-- WittVector/Identities.lean

-- WittVector/InitTail.lean

-- WittVector/IsPoly.lean

-- WittVector/Isocrystal.lean

-- WittVector/MulCoeff.lean

-- WittVector/MulP.lean

-- WittVector/StructurePolynomial.lean

-- WittVector/Teichmuller.lean

-- WittVector/Truncated.lean

-- WittVector/Verschiebung.lean

-- WittVector/WittPolynomial.lean

-- ZMod.lean
