/-
Generated by origin.py from Data/Finsupp/Option.lean
Genuine declarations: 20 of 24 total
Dissolved: 3
Infrastructure skipped: 1
-/
import Origin.Core

/-! # Data.Finsupp on Option α -/

universe u
variable {α : Type u}

def some (f : Option α →₀ M) : α →₀ M :=
  f.comapDomain Option.some fun _ => by simp

theorem some_zero : (0 : Option α →₀ M).some = 0 := by
  ext
  simp

theorem some_add [AddZeroClass M] (f g : Option α →₀ M) : (f + g).some = f.some + g.some := by
  ext
  simp

theorem some_single_none (m : M) : (single none m : Option α →₀ M).some = 0 := by
  ext
  simp

theorem some_single_some (a : α) (m : M) :
    (single (Option.some a) m : Option α →₀ M).some = single a m := by
  classical
    ext b
    simp [single_apply]

theorem embDomain_some_some (f : α →₀ M) (x) : f.embDomain .some (.some x) = f x := by
  simp [← Function.Embedding.some_apply]

theorem some_update_none (f : Option α →₀ M) (a : M) :
    (f.update none a).some = f.some := by
  ext
  simp [Finsupp.update]

def optionEquiv : (Option α →₀ M) ≃ M × (α →₀ M) where
  toFun P := (P none, P.some)
  invFun P := (P.2.embDomain .some).update none P.1
  left_inv P := by ext (_ | a) <;> simp [Finsupp.update]
  right_inv P := by ext <;> simp [Finsupp.update]

def optionElim (y : M) (f : α →₀ M) : Option α →₀ M :=
  optionEquiv.invFun (y, f)

lemma optionElim_apply_none (y : M) (f : α →₀ M) : f.optionElim y none = y := by
  classical
  simp [optionElim]

lemma optionElim_apply_some (y : M) (f : α →₀ M) (x : α) :
    f.optionElim y (Option.some x) = f x := by
  classical
  simp [optionElim]

lemma optionElim_apply_eq_elim (y : M) (f : α →₀ M) (a : Option α) :
    f.optionElim y a = a.elim y f := by
  cases a with
  | none => exact optionElim_apply_none y f
  | some x => simp only [optionElim_apply_some, Option.elim_some]

lemma optionElim_eq_elim' (y : M) (f : α →₀ M) (a : Option α) :
    optionElim y f a = Option.elim' y f a := by
  rw [optionElim_apply_eq_elim, Option.elim'_eq_elim]

lemma some_optionElim (y : M) (f : α →₀ M) : (f.optionElim y).some = f := by
  ext
  simp

lemma optionElim_some (f : Option α →₀ M) : f.some.optionElim (f none) = f := by
  ext a
  cases a
  · rw [optionElim_apply_none]
  · simp

theorem optionElim_zero (y : M) : (0 : α →₀ M).optionElim y = single none y := by
  ext a
  cases a
  · simp
  · simp

theorem eq_option_embedding_update_none_iff {n : Option α →₀ M} {m : α →₀ M} {i : M} :
    n = (embDomain Embedding.some m).update none i ↔ n none = i ∧ n.some = m :=
  (optionEquiv.apply_eq_iff_eq_symm_apply (y := (_, _))).symm.trans Prod.ext_iff

theorem prod_option_index [AddZeroClass M] [CommMonoid N] (f : Option α →₀ M)
    (b : Option α → M → N) (h_zero : ∀ o, b o 0 = 1)
    (h_add : ∀ o m₁ m₂, b o (m₁ + m₂) = b o m₁ * b o m₂) :
    f.prod b = b none (f none) * f.some.prod fun a => b (Option.some a) := by
  classical
    induction f using induction_linear with
    | zero => simp [some_zero, h_zero]
    | add f₁ f₂ h₁ h₂ =>
      rw [Finsupp.prod_add_index, h₁, h₂, some_add, Finsupp.prod_add_index]
      · simp only [h_add, Pi.add_apply, Finsupp.coe_add]
        rw [mul_mul_mul_comm]
      all_goals simp [h_zero, h_add]
    | single a m => cases a <;> simp [h_zero]

theorem sum_option_index_smul [Semiring R] [AddCommMonoid M] [Module R M] (f : Option α →₀ R)
    (b : Option α → M) :
    (f.sum fun o r => r • b o) = f none • b none + f.some.sum fun a r => r • b (Option.some a) :=
  f.sum_option_index _ (fun _ => zero_smul _ _) fun _ _ _ => add_smul _ _ _

lemma optionElim_add [AddZeroClass M] (a b : α →₀ M) (i j : M) :
    (a + b).optionElim (i + j) = a.optionElim i + b.optionElim j := by
  ext x; cases x <;> simp

