/-
Generated by origin.py from Analysis/Normed/Ring/TransferInstance.lean
Genuine declarations: 2 of 2 total
Dissolved: 0
Infrastructure skipped: 0
-/
import Origin.Core

/-! # Analysis.Normed.Ring on Option α -/

universe u
variable {α : Type u}

protected abbrev seminormedRing [SeminormedRing β] (e : α ≃ β) :
    SeminormedRing α :=
  letI := e.ring
  .induced α β e.ringEquiv

protected abbrev normedRing [NormedRing β] (e : α ≃ β) : NormedRing α :=
  letI := e.ring
  .induced α β e.ringEquiv e.injective

