/-
Extracted from Topology/Spectral/ConstructibleTopology.lean
Genuine: 1 of 1 | Dissolved: 0 | Infrastructure: 0
-/
import Origin.Core

/-!
# Constructible topology

In this file we define the constructible topology on a topological space. This is the topology
generated by compact open subsets and their complements.

## Main definitions and results

- `WithConstructibleTopology`: `X` equipped with its constructible topology.
- `compactSpace_withConstructibleTopology`: If `X` is quasi-separated, quasi-sober,
  prespectral and quasi-compact, then `X` is still quasi-compact in the constructible topology.

## TODOs

- If `X` is a spectral space, show that `X` is T2 and totally disconnected (@chrisflav).
-/

variable {X : Type*} [TopologicalSpace X]

def constructibleTopologySubbasis (X : Type*) [TopologicalSpace X] : Set (Set X) :=
  { s | IsOpen s ∧ IsCompact s } ∪ { s | IsClosed s ∧ IsCompact sᶜ }
