/-
Generated by origin.py from Algebra/Order/Interval/Basic.lean
Genuine declarations: 32 of 85 total
Dissolved: 1
Infrastructure skipped: 52
-/
import Origin.Core

/-! # Algebra.Order.Interval on Option α -/

universe u
variable {α : Type u}

theorem coe_one : ((1 : NonemptyInterval α) : Set α) = 1 :=
  coe_pure _

theorem one_mem_one : (1 : α) ∈ (1 : NonemptyInterval α) :=
  ⟨le_rfl, le_rfl⟩

theorem coe_one : ((1 : Interval α) : Set α) = 1 :=
  Icc_self _

theorem one_mem_one : (1 : α) ∈ (1 : Interval α) :=
  ⟨le_rfl, le_rfl⟩

theorem bot_mul : ⊥ * t = ⊥ :=
  WithBot.map₂_bot_left _ _

theorem mul_bot : s * ⊥ = ⊥ :=
  WithBot.map₂_bot_right _ _

theorem coe_pow_interval [CommMonoid α] [Preorder α] [IsOrderedMonoid α]
    (s : NonemptyInterval α) (n : ℕ) :
    ↑(s ^ n) = (s : Interval α) ^ n :=
  map_pow (⟨⟨(↑), coe_one_interval⟩, coe_mul_interval⟩ : NonemptyInterval α →* Interval α) _ _

theorem sub_mem_sub (ha : a ∈ s) (hb : b ∈ t) : a - b ∈ s - t :=
  ⟨tsub_le_tsub ha.1 hb.2, tsub_le_tsub ha.2 hb.1⟩

theorem bot_sub : ⊥ - t = ⊥ :=
  WithBot.map₂_bot_left _ _

theorem sub_bot : s - ⊥ = ⊥ :=
  WithBot.map₂_bot_right _ _

theorem div_mem_div (ha : a ∈ s) (hb : b ∈ t) : a / b ∈ s / t :=
  ⟨div_le_div'' ha.1 hb.2, div_le_div'' ha.2 hb.1⟩

theorem bot_div : ⊥ / t = ⊥ :=
  WithBot.map₂_bot_left _ _

theorem div_bot : s / ⊥ = ⊥ :=
  WithBot.map₂_bot_right _ _

theorem inv_mem_inv (ha : a ∈ s) : a⁻¹ ∈ s⁻¹ :=
  ⟨inv_le_inv' ha.2, inv_le_inv' ha.1⟩

protected theorem mul_eq_one_iff : s * t = 1 ↔ ∃ a b, s = pure a ∧ t = pure b ∧ a * b = 1 := by
  refine ⟨fun h => ?_, ?_⟩
  · rw [NonemptyInterval.ext_iff, Prod.ext_iff] at h
    have := (mul_le_mul_iff_of_ge s.fst_le_snd t.fst_le_snd).1 (h.2.trans h.1.symm).le
    refine ⟨s.fst, t.fst, ?_, ?_, h.1⟩ <;> apply NonemptyInterval.ext <;> dsimp [pure]
    · nth_rw 2 [this.1]
    · nth_rw 2 [this.2]
  · rintro ⟨b, c, rfl, rfl, h⟩
    rw [pure_mul_pure, h, pure_one]

protected theorem mul_eq_one_iff : s * t = 1 ↔ ∃ a b, s = pure a ∧ t = pure b ∧ a * b = 1 := by
  cases s
  · simp
  cases t
  · simp
  · simp_rw [← NonemptyInterval.coe_mul_interval, ← NonemptyInterval.coe_one_interval,
      Interval.coe_inj, NonemptyInterval.coe_eq_pure]
    exact NonemptyInterval.mul_eq_one_iff

def length : α :=
  s.snd - s.fst

theorem length_nonneg : 0 ≤ s.length :=
  sub_nonneg_of_le s.fst_le_snd

theorem length_pure : (pure a).length = 0 :=
  sub_self _

theorem length_zero : (0 : NonemptyInterval α).length = 0 :=
  length_pure _

theorem length_neg : (-s).length = s.length :=
  neg_sub_neg _ _

theorem length_add : (s + t).length = s.length + t.length :=
  add_sub_add_comm _ _ _ _

theorem length_sub : (s - t).length = s.length + t.length := by simp [sub_eq_add_neg]

theorem length_sum (f : ι → NonemptyInterval α) (s : Finset ι) :
    (∑ i ∈ s, f i).length = ∑ i ∈ s, (f i).length :=
  map_sum (⟨⟨length, length_zero⟩, length_add⟩ : NonemptyInterval α →+ α) _ _

def length : Interval α → α
  | ⊥ => 0
  | (s : NonemptyInterval α) => s.length

theorem length_nonneg : ∀ s : Interval α, 0 ≤ s.length
  | ⊥ => le_rfl
  | (s : NonemptyInterval α) => s.length_nonneg

theorem length_pure : (pure a).length = 0 :=
  NonemptyInterval.length_pure _

theorem length_zero : (0 : Interval α).length = 0 :=
  length_pure _

theorem length_neg : ∀ s : Interval α, (-s).length = s.length
  | ⊥ => rfl
  | (s : NonemptyInterval α) => s.length_neg

theorem length_add_le : ∀ s t : Interval α, (s + t).length ≤ s.length + t.length
  | ⊥, _ => by simp
  | _, ⊥ => by simp
  | (s : NonemptyInterval α), (t : NonemptyInterval α) => (s.length_add t).le

theorem length_sub_le : (s - t).length ≤ s.length + t.length := by
  simpa [sub_eq_add_neg] using length_add_le s (-t)

theorem length_sum_le (f : ι → Interval α) (s : Finset ι) :
    (∑ i ∈ s, f i).length ≤ ∑ i ∈ s, (f i).length :=
  Finset.le_sum_of_subadditive _ length_zero.le length_add_le _ _

