/-
Extracted from Analysis/CStarAlgebra/ContinuousFunctionalCalculus/Range.lean
Genuine: 5 of 5 | Dissolved: 0 | Infrastructure: 0
-/
import Origin.Core

/-! # Range of the continuous functional calculus

This file contains results about the range of the continuous functional calculus, and
consequences thereof.

## Main results

* `range_cfcHom_le` and `range_cfcₙHom_le`: for `RCLike` scalar rings, the range of the continuous
  functional calculus homomorphism is contained in the elemental subalgebra generated by the given
  element. When the continuous functional calculus homomorphism is a closed embedding, this
  containment is in fact an equality, as found in `range_cfcHom` and `range_cfcₙHom`
* `range_cfc_nnreal_subset` and `range_cfcₙ_nnreal_subset`: over the scalar semiring `ℝ≥0`, the
  range of the continuous functional calculus consists of the nonnegative elements in the elemental
  `ℝ`-algebra generated by the given element. Again, when the continuous functional calculus
  homomorphism is a closed embedding, this containment is an equality, see `range_cfc_nnreal_subset`
  and `range_cfcₙ_nnreal_subset`.
* `cfc_mem` and `cfcₙ_mem`: the continuous functional calculus of an element is contained in any
  closed star subalgebra containing the element.

-/

open Topology

open scoped CStarAlgebra

section Unital

section RCLike

variable (𝕜 : Type*) {A : Type*} {p : A → Prop} [RCLike 𝕜] [Ring A] [StarRing A] [Algebra 𝕜 A]

variable [TopologicalSpace A] [StarModule 𝕜 A]

open StarAlgebra

section ClosedEmbedding

variable [ClosedEmbeddingContinuousFunctionalCalculus 𝕜 A p]

variable [IsTopologicalRing A] [ContinuousStar A]

open scoped ContinuousFunctionalCalculus in

theorem range_cfcHom {a : A} (ha : p a) :
    (cfcHom ha (R := 𝕜)).range = elemental 𝕜 a := by
  rw [StarAlgHom.range_eq_map_top, ← ContinuousMap.elemental_id_eq_top, StarAlgebra.elemental,
    ← StarSubalgebra.topologicalClosure_map _ _ (cfcHom_isClosedEmbedding ha (R := 𝕜)).isClosedMap
      (cfcHom_continuous ha), StarAlgHom.map_adjoin]
  congr
  simpa using cfcHom_id ha

lemma range_cfc {a : A} (ha : p a) : Set.range (cfc (R := 𝕜) · a) = elemental 𝕜 a := by
  rw [range_cfc_eq_range_cfcHom 𝕜 ha, range_cfcHom 𝕜 ha]

end ClosedEmbedding

variable [ContinuousFunctionalCalculus 𝕜 A p]

variable [IsTopologicalRing A] [ContinuousStar A]

open scoped ContinuousFunctionalCalculus in

theorem range_cfcHom_le {a : A} (ha : p a) :
    (cfcHom ha (R := 𝕜)).range ≤ elemental 𝕜 a := by
  grw [StarAlgHom.range_eq_map_top, ← ContinuousMap.elemental_id_eq_top, StarAlgebra.elemental,
    StarSubalgebra.map_topologicalClosure_le _ _ (cfcHom_continuous ha (R := 𝕜)),
    StarAlgHom.map_adjoin]
  simp [cfcHom_id ha, elemental]

lemma range_cfc_subset {a : A} (ha : p a) : Set.range (cfc (R := 𝕜) · a) ⊆ elemental 𝕜 a := by
  grw [range_cfc_eq_range_cfcHom 𝕜 ha, range_cfcHom_le 𝕜 ha]

variable {𝕜}

theorem cfcHom_mem_elemental {a : A} (ha : p a) (f : C(spectrum 𝕜 a, 𝕜)) :
    cfcHom ha f ∈ elemental 𝕜 a :=
  range_cfcHom_le 𝕜 ha ⟨f, rfl⟩
