/-
Generated by origin.py from Topology/Category/Born.lean
Genuine declarations: 1 of 5 total
Dissolved: 0
Infrastructure skipped: 4
-/
import Origin.Core

/-! # Topology.Category on Option α -/

universe u
variable {α : Type u}

structure Born where
  /-- Construct a bundled `Born` from a `Bornology`. -/
  of ::
  /-- The underlying bornology. -/
  carrier : Type*
  [str : Bornology carrier]

