/-
Generated by origin.py from Topology/Category/FinTopCat.lean
Genuine declarations: 2 of 11 total
Dissolved: 0
Infrastructure skipped: 9
-/
import Origin.Core

/-! # Topology.Category on Option α -/

universe u
variable {α : Type u}

structure FinTopCat where
  /-- carrier of a finite topological space. -/
  toTop : TopCat.{u} -- TODO: turn this into an `extends`?
  [fintype : Fintype toTop]

def of (X : Type u) [Fintype X] [TopologicalSpace X] : FinTopCat where
  toTop := TopCat.of X
  fintype := ‹_›

