/-
Released under MIT license.
-/
import Val.RingTheory.Core

/-!
# Val α: RingTheory — Ideals

Ideal sum, product, intersection, two-sided ideals, fractional ideals,
ideal quotient, and annihilator. All live in contents. Origin is outside.

Key dissolution: fractional ideals require `s ≠ 0` denominators in Mathlib.
In Val α, mul mulF (contents a) (inv invF (contents s)) = contents (...). No hypothesis.
-/

namespace Val

universe u
variable {α : Type u}

-- ============================================================================
-- Ideal Sum and Product
-- ============================================================================

/-- Ideal sum: a ∈ I + J iff a = b + c with b ∈ I, c ∈ J. -/
def idealSum (addF : α → α → α) (I J : α → Prop) : α → Prop :=
  fun a => ∃ b c, I b ∧ J c ∧ a = addF b c

/-- Ideal product: generated by products ab with a ∈ I, b ∈ J. -/
def idealProd (mulF : α → α → α) (I J : α → Prop) : α → Prop :=
  fun a => ∃ b c, I b ∧ J c ∧ a = mulF b c

theorem idealSum_in_contents (addF : α → α → α) (I J : α → Prop) (b c : α)
    (hb : I b) (hc : J c) :
    inIdeal (idealSum addF I J) (contents (addF b c) : Val α) :=
  ⟨b, c, hb, hc, rfl⟩

theorem idealProd_in_contents (mulF : α → α → α) (I J : α → Prop) (b c : α)
    (hb : I b) (hc : J c) :
    inIdeal (idealProd mulF I J) (contents (mulF b c) : Val α) :=
  ⟨b, c, hb, hc, rfl⟩

theorem origin_not_in_idealSum (addF : α → α → α) (I J : α → Prop) :
    ¬ inIdeal (idealSum addF I J) (origin : Val α) := id

theorem origin_not_in_idealProd (mulF : α → α → α) (I J : α → Prop) :
    ¬ inIdeal (idealProd mulF I J) (origin : Val α) := id

-- ============================================================================
-- Ideal Intersection and Containment
-- ============================================================================

/-- Ideal intersection. -/
def idealInter (I J : α → Prop) : α → Prop :=
  fun a => I a ∧ J a

theorem idealInter_in_contents (I J : α → Prop) (a : α) (hI : I a) (hJ : J a) :
    inIdeal (idealInter I J) (contents a : Val α) :=
  ⟨hI, hJ⟩

theorem ideal_containment (I J : α → Prop)
    (h : ∀ a, I a → J a) (a : α) (ha : inIdeal I (contents a : Val α)) :
    inIdeal J (contents a) :=
  h a ha

-- ============================================================================
-- Two-Sided Ideals
-- ============================================================================

theorem two_sided_left (mulF : α → α → α) (I : α → Prop)
    (hI : ∀ r a, I a → I (mulF r a)) (r a : α)
    (ha : inIdeal I (contents a : Val α)) :
    inIdeal I (mul mulF (contents r) (contents a)) :=
  hI r a ha

theorem two_sided_right (mulF : α → α → α) (I : α → Prop)
    (hI : ∀ a r, I a → I (mulF a r)) (a r : α)
    (ha : inIdeal I (contents a : Val α)) :
    inIdeal I (mul mulF (contents a) (contents r)) :=
  hI a r ha

-- ============================================================================
-- Fractional Ideals: The s ≠ 0 Dissolution
-- ============================================================================

/-- Fractional ideal element: a/s in contents. No s ≠ 0 hypothesis. -/
def fractionalElem (mulF : α → α → α) (invF : α → α) (a s : α) : Val α :=
  mul mulF (contents a) (inv invF (contents s))

theorem fractionalElem_is_contents (mulF : α → α → α) (invF : α → α) (a s : α) :
    fractionalElem mulF invF a s = contents (mulF a (invF s)) := rfl

theorem fractionalElem_ne_origin (mulF : α → α → α) (invF : α → α) (a s : α) :
    fractionalElem mulF invF a s ≠ (origin : Val α) := by simp [fractionalElem]

theorem fractionalElem_mul (mulF : α → α → α) (invF : α → α) (a b s t : α) :
    mul mulF (fractionalElem mulF invF a s) (fractionalElem mulF invF b t) =
    contents (mulF (mulF a (invF s)) (mulF b (invF t))) := rfl

-- ============================================================================
-- Ideal Quotient and Annihilator
-- ============================================================================

/-- Ideal quotient (colon ideal): (I : J) = { r | rJ ⊆ I }. -/
def idealQuot (mulF : α → α → α) (I J : α → Prop) : α → Prop :=
  fun r => ∀ a, J a → I (mulF r a)

theorem idealQuot_in_contents (mulF : α → α → α) (I J : α → Prop) (r : α)
    (h : ∀ a, J a → I (mulF r a)) :
    inIdeal (idealQuot mulF I J) (contents r : Val α) :=
  h

theorem origin_not_in_idealQuot (mulF : α → α → α) (I J : α → Prop) :
    ¬ inIdeal (idealQuot mulF I J) (origin : Val α) := id

/-- Annihilator of a set. -/
def annihilator (mulF : α → α → α) (target : α → Prop) (a : α) : α → Prop :=
  fun r => target (mulF r a)

theorem annihilator_in_contents (mulF : α → α → α) (target : α → Prop) (a r : α)
    (h : target (mulF r a)) :
    inIdeal (annihilator mulF target a) (contents r : Val α) :=
  h

end Val
